// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseLocalFolder():Promise<string>;

export function CreateDriveFolder(arg1:string,arg2:string):Promise<main.FolderItem>;

export function GetDriveFolders():Promise<Array<main.FolderItem>>;

export function GetStatus():Promise<Record<string, any>>;

export function HideToTray():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function OpenLocalFolder():Promise<void>;

export function Quit():Promise<void>;

export function SaveSettings(arg1:main.Config):Promise<void>;

export function SetTray(arg1:main.TrayManager):Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleAutostart(arg1:boolean):Promise<void>;

export function TriggerAuth():Promise<void>;

export function TriggerRestore():Promise<void>;

export function TriggerStop():Promise<void>;

export function TriggerSync():Promise<void>;

export function TriggerVerify():Promise<void>;
