// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseLocalFolder() {
  return window['go']['main']['App']['ChooseLocalFolder']();
}

export function CreateDriveFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateDriveFolder'](arg1, arg2);
}

export function GetDriveFolders() {
  return window['go']['main']['App']['GetDriveFolders']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenLocalFolder() {
  return window['go']['main']['App']['OpenLocalFolder']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetTray(arg1) {
  return window['go']['main']['App']['SetTray'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ToggleAutostart(arg1) {
  return window['go']['main']['App']['ToggleAutostart'](arg1);
}

export function TriggerAuth() {
  return window['go']['main']['App']['TriggerAuth']();
}

export function TriggerRestore() {
  return window['go']['main']['App']['TriggerRestore']();
}

export function TriggerStop() {
  return window['go']['main']['App']['TriggerStop']();
}

export function TriggerSync() {
  return window['go']['main']['App']['TriggerSync']();
}

export function TriggerVerify() {
  return window['go']['main']['App']['TriggerVerify']();
}
